### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#552]
_TO DO: Link to existing GH issues and create new ones as needed. For now I'm just getting this down somewhere public._

## Beta

- [ ] Login in the UI
- [ ] Add API key management UI
- [ ] Fix UI bug
- [ ] Refine details of Asset/DataSource association
- [ ] Developer docs with overview of components (client, server, adapter, catalog, authenticators, serializers and deserliaizers, queries)

## Of possible interest to Diamond

- [ ] read raw/direct/bytes
- [ ] `PATCH /table/...`

## Of interest to C2QA (tutorial coming in Oct)

- [ ] Support for unknown structures

## Of interesting to IRIS-HEP (talk coming in Oct)

- [ ] Awkward support

## Of interest to power users

- [ ] Local catalog

**Comment by danielballan** [comment]
I'm going to close this now, not because it's done, but because the GH Milestones are the best canonical location for this, and I've finally gotten around to updating them.

* [v0.1.0b1](https://github.com/bluesky/tiled/milestone/3)
* [v0.1.0](https://github.com/bluesky/tiled/milestone/1)
